### PR TITLE
rm cluster no. from csv and png result

### PR DESCRIPTION
**Pull request by paulamool**
Just removed cluster number from the CSV and PNG output in results file

### CODE REVIEW

**Comment by darcyabjones** [comment]
I can't see how the change you made removes the  cluster number from the result.

```
subtab.any(axis=0)
```
Selects each row where at least 1 element is true
axis = 1 (default) will select columns where at least 1 element is true.

Is the latter what you want?

**Comment by paulamool** [comment]
hi @darcyabjones the cluster number was being added to the results output data frame it was interfering  with the plots. I just changed subtab.any(axis=0) to subtab.any() and the results look ok?

**Comment by darcyabjones** [comment]
Ok sure.
Sorry about the questions, I'm sure its fine, I'm just trying to get my head around it.

There isn't supposed to be a column containing the cluster number in the dataframe.
It gets stored as a separate list in that Tree object.
Maybe it gets automatically added when pandas does the groupby?
If so that must be a difference between pandas versions.

Anyway a more reliable way to remove it would be to use `drop`.
<https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html>

What happens if you set `axis = 1` ?
I was wrong, apparently 0 is the default with any.
Now that I look at the code properly `subtab.any(axis=1)` would be the right thing to put in there.

**Comment by paulamool** [comment]
@darcyabjones output is the same for subtab.any(axis=1) and subtab.any() will close this and do another  pull request

**Pull request closed without merging**
